/* Generated by re2c 3.1 on Wed Apr 29 12:54:31 2026 */
#line 1 "tokenizer_template.cpp"
// re2c tokenizer_template.cpp -o tokenizer.cc
#include <cstring>

#include "import/quad_model/lexer/token.h"
#include "import/quad_model/lexer/tokenizer.h"
#include "system/string_manager.h"

#line 11 "tokenizer.cc"
#define YYMAXFILL 36
#line 8 "tokenizer_template.cpp"

constexpr size_t MQLTokenizer_SIZE = StringManager::MAX_STRING_SIZE;

MQLTokenizer::MQLTokenizer() :
    _str(new char[MQLTokenizer_SIZE + YYMAXFILL]),
    buf(new char[MQLTokenizer_SIZE + YYMAXFILL]),
    lim(buf + MQLTokenizer_SIZE),
    cur(lim),
    mar(lim),
    token_start(lim),
    eof(false)
{ }

MQLTokenizer::~MQLTokenizer()
{
    delete[] buf;
    delete[] str;
}

void MQLTokenizer::begin(MDBIstream& in)
{
    this->in = &in;
}

bool MQLTokenizer::fill(size_t need)
{
    if (eof) {
        return false;
    }
    const size_t free = token_start - buf;
    if (free < need) {
        return false;
    }
    memmove(buf, token_start, lim - token_start);
    lim -= free;
    cur -= free;
    mar -= free;
    token_start -= free;
    auto r = in->read(lim, free);
    lim += r;

    if (lim < buf + MQLTokenizer_SIZE) {
        if (r == 0)
            return false;
        eof = true;
        memset(lim, 0, YYMAXFILL);
        lim += YYMAXFILL - 1;
    }
    return true;
}

Import::QuadModel::Token MQLTokenizer::get_token()
{
    auto res = _get_token();

    str_len = cur - token_start;

    std::memcpy(_str, token_start, str_len);
    _str[str_len] = '\0';

    str = _str;

    return res;
}

Import::QuadModel::Token MQLTokenizer::_get_token()
{
    token_start = cur;
    
#line 83 "tokenizer.cc"
{
	char yych;
	unsigned int yyaccept = 0;
	if ((lim - cur) < 36) if (!fill(36)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy3;
		case '\n': goto yy5;
		case '"': goto yy6;
		case '+': goto yy7;
		case ',': goto yy8;
		case '-': goto yy9;
		case '.': goto yy10;
		case '0': goto yy11;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy13;
		case ':': goto yy14;
		case '<': goto yy15;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e': goto yy16;
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		case '[': goto yy20;
		case ']': goto yy21;
		case '_': goto yy22;
		case 'f': goto yy23;
		case 't': goto yy24;
		default: goto yy1;
	}
yy1:
	++cur;
yy2:
#line 122 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::UNRECOGNIZED; }
#line 173 "tokenizer.cc"
yy3:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy3;
		default: goto yy4;
	}
yy4:
#line 117 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::WHITESPACE; }
#line 187 "tokenizer.cc"
yy5:
	++cur;
#line 121 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::ENDLINE; }
#line 192 "tokenizer.cc"
yy6:
	yyaccept = 0;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\n': goto yy2;
		default: goto yy26;
	}
yy7:
	yyaccept = 0;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy31;
		default: goto yy2;
	}
yy8:
	++cur;
#line 120 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::COMMA; }
#line 221 "tokenizer.cc"
yy9:
	yyaccept = 0;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy31;
		case '>': goto yy33;
		default: goto yy2;
	}
yy10:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy34;
		default: goto yy2;
	}
yy11:
	yyaccept = 1;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy36;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy37;
		case 'E':
		case 'e': goto yy38;
		case 'X':
		case 'x': goto yy39;
		default: goto yy12;
	}
yy12:
#line 115 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::INTEGER; }
#line 289 "tokenizer.cc"
yy13:
	yyaccept = 1;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy36;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy37;
		case 'E':
		case 'e': goto yy38;
		default: goto yy12;
	}
yy14:
	++cur;
#line 104 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::COLON; }
#line 323 "tokenizer.cc"
yy15:
	yych = *++cur;
	switch (yych) {
		case '-': goto yy40;
		default: goto yy2;
	}
yy16:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy43;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy44;
		default: goto yy19;
	}
yy17:
#line 114 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::IDENTIFIER; }
#line 361 "tokenizer.cc"
yy18:
	yyaccept = 2;
	mar = ++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
yy19:
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy41;
		case '(': goto yy42;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case '_': goto yy45;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy17;
	}
yy20:
	++cur;
#line 118 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::L_BRACKET; }
#line 442 "tokenizer.cc"
yy21:
	++cur;
#line 119 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::R_BRACKET; }
#line 447 "tokenizer.cc"
yy22:
	yyaccept = 0;
	yych = *(mar = ++cur);
	switch (yych) {
		case 'A':
		case 'a': goto yy47;
		default: goto yy2;
	}
yy23:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy43;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy44;
		case 'a': goto yy48;
		default: goto yy19;
	}
yy24:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy41;
		case '(': goto yy42;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		case 'r': goto yy49;
		default: goto yy46;
	}
yy25:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
yy26:
	switch (yych) {
		case '\n': goto yy27;
		case '"': goto yy28;
		case '\\': goto yy29;
		default: goto yy25;
	}
yy27:
	cur = mar;
	switch (yyaccept) {
		case 0: goto yy2;
		case 1: goto yy12;
		case 2: goto yy17;
		case 3: goto yy35;
		case 4: goto yy71;
		case 5: goto yy78;
		default: goto yy87;
	}
yy28:
	++cur;
#line 109 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::STRING; }
#line 572 "tokenizer.cc"
yy29:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	goto yy25;
yy30:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy34;
		default: goto yy27;
	}
yy31:
	yyaccept = 1;
	mar = ++cur;
	if ((lim - cur) < 3) if (!fill(3)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
yy32:
	switch (yych) {
		case '.': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy31;
		case 'E':
		case 'e': goto yy50;
		default: goto yy12;
	}
yy33:
	++cur;
#line 106 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::R_ARROW; }
#line 618 "tokenizer.cc"
yy34:
	yyaccept = 3;
	mar = ++cur;
	if ((lim - cur) < 3) if (!fill(3)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy34;
		case 'E':
		case 'e': goto yy50;
		default: goto yy35;
	}
yy35:
#line 116 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::FLOAT; }
#line 642 "tokenizer.cc"
yy36:
	yyaccept = 1;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy51;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy52;
		case 'E':
		case 'e': goto yy53;
		default: goto yy12;
	}
yy37:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy52;
		default: goto yy27;
	}
yy38:
	yych = *++cur;
	switch (yych) {
		case '+':
		case '-': goto yy54;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy55;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy52;
		default: goto yy27;
	}
yy39:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy56;
		default: goto yy27;
	}
yy40:
	++cur;
#line 105 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::L_ARROW; }
#line 759 "tokenizer.cc"
yy41:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy41;
		case '(': goto yy42;
		default: goto yy27;
	}
yy42:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy42;
		case '"': goto yy57;
		default: goto yy27;
	}
yy43:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy58;
		default: goto yy46;
	}
yy44:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy58;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy59;
		default: goto yy19;
	}
yy45:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
yy46:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy45;
		default: goto yy17;
	}
yy47:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy60;
		default: goto yy27;
	}
yy48:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy58;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy59;
		case 'l': goto yy62;
		default: goto yy19;
	}
yy49:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy41;
		case '(': goto yy42;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		case 'u': goto yy63;
		default: goto yy46;
	}
yy50:
	yych = *++cur;
	switch (yych) {
		case '+':
		case '-': goto yy54;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy64;
		default: goto yy27;
	}
yy51:
	yyaccept = 1;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy66;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy67;
		case 'E':
		case 'e': goto yy68;
		default: goto yy12;
	}
yy52:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy67;
		default: goto yy27;
	}
yy53:
	yych = *++cur;
	switch (yych) {
		case '+':
		case '-': goto yy54;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy69;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy67;
		default: goto yy27;
	}
yy54:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy64;
		default: goto yy27;
	}
yy55:
	yyaccept = 3;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy69;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy67;
		default: goto yy35;
	}
yy56:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy70;
		default: goto yy27;
	}
yy57:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\n': goto yy27;
		case '"': goto yy72;
		case '\\': goto yy73;
		default: goto yy57;
	}
yy58:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy74;
		default: goto yy46;
	}
yy59:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy74;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy75;
		default: goto yy19;
	}
yy60:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy60;
		default: goto yy61;
	}
yy61:
#line 110 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::ANON; }
#line 1273 "tokenizer.cc"
yy62:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy41;
		case '(': goto yy42;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		case 's': goto yy76;
		default: goto yy46;
	}
yy63:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy41;
		case '(': goto yy42;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		case 'e': goto yy77;
		default: goto yy46;
	}
yy64:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
yy65:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy64;
		default: goto yy35;
	}
yy66:
	yyaccept = 1;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy79;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy80;
		case 'E':
		case 'e': goto yy81;
		default: goto yy12;
	}
yy67:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy80;
		default: goto yy27;
	}
yy68:
	yych = *++cur;
	switch (yych) {
		case '+':
		case '-': goto yy54;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy82;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy80;
		default: goto yy27;
	}
yy69:
	yyaccept = 3;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy82;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy80;
		default: goto yy35;
	}
yy70:
	yyaccept = 4;
	mar = ++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy56;
		default: goto yy71;
	}
yy71:
#line 112 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::HEX_ID; }
#line 1562 "tokenizer.cc"
yy72:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy72;
		case ')': goto yy83;
		default: goto yy27;
	}
yy73:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	goto yy57;
yy74:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy84;
		default: goto yy46;
	}
yy75:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy84;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy85;
		default: goto yy19;
	}
yy76:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy41;
		case '(': goto yy42;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		case 'e': goto yy86;
		default: goto yy46;
	}
yy77:
	yyaccept = 5;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy41;
		case '(': goto yy42;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case '_': goto yy45;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy78;
	}
yy78:
#line 107 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::K_TRUE; }
#line 1771 "tokenizer.cc"
yy79:
	yyaccept = 1;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy88;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy89;
		case 'E':
		case 'e': goto yy90;
		default: goto yy12;
	}
yy80:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy89;
		default: goto yy27;
	}
yy81:
	yych = *++cur;
	switch (yych) {
		case '+':
		case '-': goto yy54;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy91;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy89;
		default: goto yy27;
	}
yy82:
	yyaccept = 3;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy91;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy89;
		default: goto yy35;
	}
yy83:
	++cur;
#line 111 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::TYPED_STRING; }
#line 1889 "tokenizer.cc"
yy84:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy92;
		default: goto yy46;
	}
yy85:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy92;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy93;
		default: goto yy19;
	}
yy86:
	yyaccept = 6;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy41;
		case '(': goto yy42;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case '_': goto yy45;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy87;
	}
yy87:
#line 108 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::K_FALSE; }
#line 2021 "tokenizer.cc"
yy88:
	yyaccept = 1;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy94;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy95;
		case 'E':
		case 'e': goto yy96;
		default: goto yy12;
	}
yy89:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy95;
		default: goto yy27;
	}
yy90:
	yych = *++cur;
	switch (yych) {
		case '+':
		case '-': goto yy54;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy97;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy95;
		default: goto yy27;
	}
yy91:
	yyaccept = 3;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy97;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy95;
		default: goto yy35;
	}
yy92:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy98;
		default: goto yy46;
	}
yy93:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy98;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy99;
		default: goto yy19;
	}
yy94:
	yyaccept = 1;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy100;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f': goto yy101;
		case 'E':
		case 'e': goto yy102;
		default: goto yy12;
	}
yy95:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy101;
		default: goto yy27;
	}
yy96:
	yych = *++cur;
	switch (yych) {
		case '+':
		case '-': goto yy54;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy103;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy101;
		default: goto yy27;
	}
yy97:
	yyaccept = 3;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy103;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy101;
		default: goto yy35;
	}
yy98:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy104;
		default: goto yy46;
	}
yy99:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy104;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy105;
		default: goto yy19;
	}
yy100:
	yyaccept = 1;
	yych = *(mar = ++cur);
	switch (yych) {
		case '-': goto yy106;
		default: goto yy32;
	}
yy101:
	yych = *++cur;
	switch (yych) {
		case '-': goto yy106;
		default: goto yy27;
	}
yy102:
	yych = *++cur;
	switch (yych) {
		case '+': goto yy54;
		case '-': goto yy107;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy64;
		default: goto yy27;
	}
yy103:
	yyaccept = 3;
	yych = *(mar = ++cur);
	switch (yych) {
		case '-': goto yy106;
		default: goto yy65;
	}
yy104:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '-': goto yy106;
		default: goto yy46;
	}
yy105:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy41;
		case '(': goto yy42;
		case '-': goto yy106;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy46;
	}
yy106:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy108;
		default: goto yy27;
	}
yy107:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy109;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy108;
		default: goto yy27;
	}
yy108:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy110;
		default: goto yy27;
	}
yy109:
	yyaccept = 3;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy111;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy110;
		default: goto yy35;
	}
yy110:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy112;
		default: goto yy27;
	}
yy111:
	yyaccept = 3;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy113;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy112;
		default: goto yy35;
	}
yy112:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy114;
		default: goto yy27;
	}
yy113:
	yyaccept = 3;
	yych = *(mar = ++cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy115;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy114;
		default: goto yy35;
	}
yy114:
	yych = *++cur;
	switch (yych) {
		case '-': goto yy116;
		default: goto yy27;
	}
yy115:
	yyaccept = 3;
	yych = *(mar = ++cur);
	switch (yych) {
		case '-': goto yy116;
		default: goto yy65;
	}
yy116:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy117;
		default: goto yy27;
	}
yy117:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy118;
		default: goto yy27;
	}
yy118:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy119;
		default: goto yy27;
	}
yy119:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy120;
		default: goto yy27;
	}
yy120:
	yych = *++cur;
	switch (yych) {
		case '-': goto yy121;
		default: goto yy27;
	}
yy121:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy122;
		default: goto yy27;
	}
yy122:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy123;
		default: goto yy27;
	}
yy123:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy124;
		default: goto yy27;
	}
yy124:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy125;
		default: goto yy27;
	}
yy125:
	yych = *++cur;
	switch (yych) {
		case '-': goto yy126;
		default: goto yy27;
	}
yy126:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy127;
		default: goto yy27;
	}
yy127:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy128;
		default: goto yy27;
	}
yy128:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy129;
		default: goto yy27;
	}
yy129:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy130;
		default: goto yy27;
	}
yy130:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy131;
		default: goto yy27;
	}
yy131:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy132;
		default: goto yy27;
	}
yy132:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy133;
		default: goto yy27;
	}
yy133:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy134;
		default: goto yy27;
	}
yy134:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy135;
		default: goto yy27;
	}
yy135:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy136;
		default: goto yy27;
	}
yy136:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy137;
		default: goto yy27;
	}
yy137:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy138;
		default: goto yy27;
	}
yy138:
	++cur;
#line 113 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::UUID_ID; }
#line 3253 "tokenizer.cc"
}
#line 123 "tokenizer_template.cpp"

    return Import::QuadModel::Token::END_OF_FILE;
}
